//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zhihu_preserver.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("zhihu_preserver.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地址.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 应用.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已删除自动刷新脚本。.
        /// </summary>
        public static string AutoRefreshScriptDeleted {
            get {
                return ResourceManager.GetString("AutoRefreshScriptDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已找到自动刷新脚本。.
        /// </summary>
        public static string AutoRefreshScriptFound {
            get {
                return ResourceManager.GetString("AutoRefreshScriptFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未找到自动刷新脚本。.
        /// </summary>
        public static string AutoRefreshScriptNotFound {
            get {
                return ResourceManager.GetString("AutoRefreshScriptNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浏览.
        /// </summary>
        public static string Browsing {
            get {
                return ResourceManager.GetString("Browsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭窗口.
        /// </summary>
        public static string CloseWindow {
            get {
                return ResourceManager.GetString("CloseWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 控制面板.
        /// </summary>
        public static string ControlPanel {
            get {
                return ResourceManager.GetString("ControlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文档.
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 常规.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帮助.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主页.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 信息.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载完毕.
        /// </summary>
        public static string LoadComplete {
            get {
                return ResourceManager.GetString("LoadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载中………….
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载指定设置.
        /// </summary>
        public static string LoadSettings {
            get {
                return ResourceManager.GetString("LoadSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 多开.
        /// </summary>
        public static string Multiboxing {
            get {
                return ResourceManager.GetString("Multiboxing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新建浏览器窗口（空白页）.
        /// </summary>
        public static string NewBrowserWindowBlank {
            get {
                return ResourceManager.GetString("NewBrowserWindowBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新建浏览器窗口（主页）.
        /// </summary>
        public static string NewBrowserWindowHomePage {
            get {
                return ResourceManager.GetString("NewBrowserWindowHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新页面.
        /// </summary>
        public static string NewPage {
            get {
                return ResourceManager.GetString("NewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新标签页.
        /// </summary>
        public static string NewTab {
            get {
                return ResourceManager.GetString("NewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已打开的网页.
        /// </summary>
        public static string OpenWebPages {
            get {
                return ResourceManager.GetString("OpenWebPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 程序.
        /// </summary>
        public static string Program {
            get {
                return ResourceManager.GetString("Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 就绪.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存路径 .
        /// </summary>
        public static string SavePath {
            get {
                return ResourceManager.GetString("SavePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存网页.
        /// </summary>
        public static string SaveWebPage {
            get {
                return ResourceManager.GetString("SaveWebPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置项.
        /// </summary>
        public static string SettingsItem {
            get {
                return ResourceManager.GetString("SettingsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 状态面板.
        /// </summary>
        public static string StatusPanel {
            get {
                return ResourceManager.GetString("StatusPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统加载完毕。.
        /// </summary>
        public static string SystemLoaded {
            get {
                return ResourceManager.GetString("SystemLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务.
        /// </summary>
        public static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务队列.
        /// </summary>
        public static string TaskQueue {
            get {
                return ResourceManager.GetString("TaskQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标题.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 值.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 网页.
        /// </summary>
        public static string WebPage {
            get {
                return ResourceManager.GetString("WebPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 网页下载完成。.
        /// </summary>
        public static string WebPageDownloadComplete {
            get {
                return ResourceManager.GetString("WebPageDownloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始下载网页 .
        /// </summary>
        public static string WebPageDownloadStart {
            get {
                return ResourceManager.GetString("WebPageDownloadStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 网页解析完成。.
        /// </summary>
        public static string WebPageParseComplete {
            get {
                return ResourceManager.GetString("WebPageParseComplete", resourceCulture);
            }
        }
    }
}
